### ISSUE TITLE
Publikování na itch.io

### ISSUE THREAD

**Issue by xdub** [Trezor68/Divka-co-ztratila-sve-sny#3]
Nechtěl bys hru publikovat na itch.io?
Nemyslím tím samozřejmě hned.
Na itch.io by na ní narazilo i víc lidí.

**Comment by Trezor68** [comment]
Na itch.io už jí mám https://trezor34.itch.io/dvka-co-ztratila-sv-sny. Kolega mi poradil abych to dal i na github, tak to dávám i sem. Děkuji ale za zpětnou vazbu! Vážím si toho!

Zatím to mám na itchio nevěřejný, chci to dát plně věřejný, až to bude trošku líp vypadat.
